# AdvancedSpawners
# Made by GC

# Version: 1.0.4
# Release date: 2020.03.02

# ** Commands and permissions
# /advancedspawners - Main command; Permission: 'advancedspawners.help'

# Some configurable settings are explained, others should be self-explanatory.
# Contact "GC." on SpigotMC with any questions or bug reports.

# General Settings
settings:
  spawnersDisplay:
    # Spawner Item Name
    name: '&e%spawner type% &7Spawner'

    # Spawner Item Lore
    lore:
      - '&7Spawner Level &7%level%'
      - '&ePlace spawner down to start spawning mobs.'

    # Should spawner item be glowing?
    glowing: true

# Settings for Spawner Stacking
spawnerConfiguration:
  # Is spawner stacking enabled
  # Explanation: Spawner Stacking is combining multiple spawners into one block
  # It greatly increases server performance and reduces number of blocks players must place
  enabled: true

  # Limit of stacked spawners per one spawner block
  # Set to 0 for unlimited amount
  spawnerStackLimit: 0

  # Radius in which placed spawners will be combined
  # If set to 0, player will need to right-click spawner block for stacking
  combiningRadius: 3

  # Placing / Breaking messages
  stackInteraction:
    # Message types for placing & breaking spawners
    # Change to 'NONE' to disable
    # - CHAT
    # - ACTIONBAR
    # - NONE
    messageType: CHAT

    # Message sent if stacking is enabled
    messageStacked: '&7You placed &e%mob name%&7 spawner, new stack amount: &e%amount%&7!'

    # Message sent if stacking is disabled
    messageNoStacking: '&7You placed &e%mob name%&7 Spawner'

  # Hologram Configuration
  holograms:
    # Should static holograms on top of spawners be enabled?
    enabled: true

    # Text displayed by holograms on top of spawners
    text: '&e%mob name% &7Spawners (&ex%amount%&7)'

  # Spawning amount per Spawner in stack
  # Formats:
  # - '<min>-<max>', e.g.: '1-3', random number of mobs between 1 and 3 to be spawned per spawner
  # - '<amount>' e.g.: '1', 1 mob will be spawned per spawner
  # Whatever random number is used, it will be multiplied by number of spawners
  spawningAmount: '1-3'

  # Settings for mob stacking
  mobSettings:
    # Should mobs stack?
    # Enabling this will yield huge performance increase
    stackMobs: true

    # In what radius should mobs stack?
    # Maximum radius size: 16
    stackRadius: 16

    # Name shown on top of Mobs
    stackedMobName: "&e%mob name% &7x&e%amount%"

    # Kill whole stack? If set to false, mobs will be killed one by one
    killWholeStack: false

  # Spawner Breaking Configuration
  breaking:
    # Should all spawners break at once spawner block is broken?
    breakAll: false

    # Is silktouch enabled for spawners?
    # Players require 'advancedspawners.silktouch' permission to use this
    spawnersSilkTouch: true

    # Should broken spawners teleport to inventory?
    teleportOnBreak: false

    # Should natural spawners drop when silktouched?
    dropNatural: true

messages:
  playerOffline: '&c&lAdvancedSpawners &cSpecified player is offline!'
  invalidMob: '&c&lAdvancedSpawners &cSpecified mob is invalid!'
  invalidNumber: '&c&lAdvancedSpawners &cSpecified number is invalid!'
  giveCommand:
    gaveSpawners: '&c&lAdvancedSpawners &7Gave &e%mob type% x%amount%&7 spawners to &e%player%'
    receivedSpawners: '&c&lAdvancedSpawners &7You received &e%mob type% x%amount%&7 spawners'
